### ISSUE TITLE
Compress/bundle data not working

### ISSUE THREAD

**Issue by jnimoth** [rijksuniversiteit-groningen/iBridges-Gui#13]
The functionality to bundle data to a tar or zip archive is currently not possible. When trying to do this via the `Compress/bundle data` tab an error message saying that there is not enough space (rootResc selected) on the resource is displayed (see screenshot).

![image](https://user-images.githubusercontent.com/109157914/179755273-ec313922-1448-4a8b-87ed-0d3ddd6f5f3b.png)

**Comment by jpmcfarland** [comment]
I believe lack of space reporting is no longer an issue, but I still don't think an archive is made.

**Comment by jpmcfarland** [comment]
Extracting larger files (350GB was tested) resulted on an error similar to that seen in Issue #8.  This is likely the same error and related to an iRODS/PRC bug.  If the functionality is otherwise acceptable, I think _this_ issue is resolved.
