### ISSUE TITLE
Fix problems in Browser tab

### ISSUE THREAD

**Issue by jpmcfarland** [rijksuniversiteit-groningen/iBridges-Gui#19]
1. Clicking on any field other than the `Name` column gives incorrect results in the lower tab views.  Only the name should be sent to the methods populating the tab views. [FIXED: #30]
2. Permissions editing appears to be broken. [FIXED #51]

**Comment by jpmcfarland** [comment]
Remove trailing `/` throughout.  Collections, unlike directories, don't have this.  Use `ils`-like collection/data object indicators instead (e.g., `C-` and `&`/`X`/`?`).

**Comment by jpmcfarland** [comment]
Not a problem, but a feature, add a `..` at the top of the `Browser` table (with index 0?) to navigate to the parent collection.

See: https://github.com/chStaiger/iBridges-Gui/issues/13

**Comment by jpmcfarland** [comment]
Add resource selection drop-down.  Currently uses default resource for uploads.

**Comment by jpmcfarland** [comment]
Convert `Path` column to `Type` column and add indication of a collection.  Also, check to see if it is feasible to populate collection `Size`s and 'Last modified` dates.

**Comment by jpmcfarland** [comment]
The `delete` button is also not working.

**Comment by simstoica** [comment]
> The `delete` button is also not working.

Which delete ? Metadata -delete or in the delete tab, delete button?

**Comment by jpmcfarland** [comment]
> > The `delete` button is also not working.
> 
> Which delete ? Metadata -delete or in the delete tab, delete button?

The red one on the right within the `Delete` view.  Nothing happens when you click on it.  After a little reflection, I see that you must first click on an object up in the table, click `Load`, then click `Delete`.  Not tremendously intuitive!  **It should be documented at least.**

**Comment by jpmcfarland** [comment]
Clicking on a collection no longer loads it.  Likely an artifact of the PyQt upgrade.
