### ISSUE TITLE
Permission assignment not possible

### ISSUE THREAD

**Issue by jnimoth** [rijksuniversiteit-groningen/iBridges-Gui#46]
The permission assignment in the  `Browser` tab of iBridges seems to be non-functional. 

I cannot assign new permissions and also cannot modify already assigned permissions. The `Permission type` and `Recursive` selections have no function in the current version (no selection is possible).  

I am currently testing the develop branch with commit deefbece17f4d75e5da0457c3536ddf3b9195c07

![iBridges_permissions_issue](https://user-images.githubusercontent.com/109157914/196668996-6ac89029-6d77-49d7-8b61-dcea97c66909.png)

**Comment by jpmcfarland** [comment]
@jnimoth This is why:

https://github.com/rijksuniversiteit-groningen/iBridges/blob/91a1d914b872eb13ddd8537e1b4879b3e96cd70b/gui/irodsBrowser.py#L52-L57

I feel this is overly restrictive and so does @simstoica.  In the RDMS GUI, there is no such restriction.  Indeed, this protects the user from her/himself!  I think it unnecessary.

Any objections to removing it?

**Comment by jpmcfarland** [comment]
ACL setting is available again and working quite well.  Just a few more tweaks and it should be ready for testing.

**Comment by jpmcfarland** [comment]
@jnimoth Give it a try!

**Comment by jnimoth** [comment]
Works!
