### ISSUE TITLE
Since pyqt6 update, selection is not possible.

### ISSUE THREAD

**Issue by jnimoth** [rijksuniversiteit-groningen/iBridges-Gui#47]
Just tested the new `develop` branch (commit deefbece17f4d75e5da0457c3536ddf3b9195c07 ) on Linux. I cannot select elements in the `Up and Download` tab or `(Un)bundle data` tab of iBridges in this version. 

When I try to click on the check boxes, nothing happens (= nothing is selected) and I get an error message that I have to select something before doing a transfer or (un)bundling data.

![image](https://user-images.githubusercontent.com/109157914/196671309-f3370edb-b310-48ff-ac0b-9f0b0e50e69c.png)

In this regard, I think it might make sense to see how pyqt6 is used in Christine's/Terrell's version. For comparison, this is how it currently looks in `pyqt6` the branch in  [Christine's iBridges version](https://github.com/chStaiger/iBridges-Gui/tree/pyqt6):

![image](https://user-images.githubusercontent.com/109157914/196672329-034cdc3a-e425-4667-8756-0bc78e19b061.png)

Here the selection is not done by selecting check boxes, but by highlighting the name of the destination.

**Comment by jpmcfarland** [comment]
Quite strange.  Obviously the API change was not fully compensated for.  I'll see if I can fix it quickly.  For now, you can use the pre-PyQt6 code:

```bash
git checkout 8e063000fbc29f7432d69921ce17f15e9807a7ae
```

**Comment by jpmcfarland** [comment]
The tree view selection is fixed and uses highlighting, but the changes have not yet been committed.  Tomorrow!

**Comment by jpmcfarland** [comment]
@jnimoth please check and approve if satisfied.

**Comment by jnimoth** [comment]
It works again with the new fix in [jpm/feature/47_fix_selection](https://github.com/rijksuniversiteit-groningen/iBridges/tree/jpm/feature/47_fix_selection)
