### ISSUE TITLE
Remove/Reduce available resources in the GUI

### ISSUE THREAD

**Issue by jnimoth** [rijksuniversiteit-groningen/iBridges-Gui#9]
Maybe one can remove or reduce the resources overview in the "Up and Download" tab and also under the "Info" tab? As far as I know upload to the RDMS should be done via rootResc, so having all resources available/visible is rather confusing. And in the info tab, there is just for rootResc and tapeResc information on the free resources space available (as explained by John, due to the rather complex resources structure of our system).

![image (1)](https://user-images.githubusercontent.com/109157914/179707733-dd8cd522-35ca-41d7-a473-83dac8defeab.png)
![image (2)](https://user-images.githubusercontent.com/109157914/179707740-1b495567-bea7-4652-ad84-2063915759ab.png)

**Comment by jpmcfarland** [comment]
The top-level resources are listed by default.  Removing them all except for the default defined in the iRODS environment precludes the possibility to use a desired alternate resource such as a tape archive (tapeResc).  The client potentially can be used in other iRODS systems and would unnecessarily limit them.

One thing I _will_ do is to remove those resources that iBridges will not use anyway, those resources without their free space indicated (seen as "no information").  When that is done, please see if this is reasonable and intuitive.  If that doesn't seem to be enough, I have other ideas we can try.

**Comment by jpmcfarland** [comment]
@jnimoth PR #20 minimizes the resource list.  If you find it resolves this issue, please close it.
